# -*- coding: utf-8 -*-
"""The restructured report's content.

Everything here is either new prose or a reference into the previous version's
paragraphs, which are reused verbatim so that no wording the supervisor has
already read changes by accident. `R(n)` reuses paragraph n of the September
document; anything in quotes is new.

Structure:
    Abstract, then one unified Introduction covering all three strands,
    then a chapter per strand, then a combined conclusion.
"""

# ── the figure plan ───────────────────────────────────────────────────
# (key, source file, placed width in points, caption)
#   NEW/   a figure generated by ../figure_src
#   MEDIA/ a picture lifted from the previous document
#   REPO/  a file elsewhere in the repository
FIGS = {}


def fig(key, src, w, cap):
    FIGS[key] = (src, w, cap)


# ── Chapter 1 ────────────────────────────────────────────────────────
fig('prior', 'NEW/fig38_prior_chassis.png', 451.0,
    'Figure 1. The geometry this platform inherits, reproduced from the prior work [1]. Panels (a) and '
    '(b) are the two chassis variants that paper proposes: in (a) the lateral wheels sit close together '
    'and in (b) they are distributed along the length. Variant (a) is the arrangement built here. Panel '
    '(c) is that paper’s kinematic schematic, with the wheel origins at longitudinal distances '
    'l₁ and l₂ from the body centre and a half track of d, which are the symbols used throughout '
    'Section 1.5.')
fig('kin', 'NEW/fig35_prior_kinematics.png', 451.0,
    'Figure 2. What the non-collinear placement changes, drawn at the dimensions of the machine built '
    'here. In the symmetric case every wheel shares one yaw lever arm. Moving one diagonal pair inward '
    'gives the two pairs lever arms of 0.5607 m and 0.4907 m, a difference of 14 per cent. The '
    'translation terms are identical between the two layouts, so only the yaw column of the '
    'transformation changes, and that is both the whole of the difference and the whole of the risk.')
fig('plat', 'MEDIA/image2.jpg', 313.6,
    'Figure 3. The platform as built. The chassis is 1.00 m long and 0.36 m wide across the wheels, and '
    'the four mecanum wheels sit non-collinearly rather than at the corners of a rectangle: the pair '
    'nearer the camera is visibly offset along the length from the pair behind. The vertical mast '
    'carries the three normal tubes and the stepper axis of the cargo arm. The mast and its payload sit '
    'within the plane of the lidar, which is the black unit above the battery, and are the cause of the '
    'self-occlusion sector measured in Section 1.12.')
fig('trial', 'MEDIA/image3.png', 420.0,
    'Figure 4. The platform during hardware trials. Panel (a) is a top-down view with the body axis '
    'convention marked and the lidar at its mounting position above the battery. Panel (b) is the '
    'corresponding view in the visualiser. Panels (c) and (d) are the start and end frames of the '
    'forward-drive test used to establish the lidar angular convention.')
fig('elec', 'REPO/docs/hardware/nab_circuit_diagram.png', 453.0,
    'Figure 5. The deployed electronics, organised in three layers: power distribution, compute and '
    'command, and drive with odometry feedback, each on its own rail colour. The front and rear motors '
    'carry encoders of different resolution and different wiring convention, which is recorded '
    'explicitly because the difference has caused a channel to be miswired during commissioning. The '
    'control constants shown against the microcontroller are the deployed ones, and they are the values '
    'derived in Section 1.6.')
fig('geom', 'MEDIA/image5.png', 419.9,
    'Figure 6. Dimensioned plan view of the wheel layout, taken from the mechanical assembly. The outer '
    'diagonal pair sits 403 mm from the body centre along the longitudinal axis and the inner pair 333 '
    'mm, an offset of 70 mm. The half track width is the same for all four wheels. Two width figures '
    'appear in this report and they measure the same span by different means. The 360 mm quoted in the '
    'hardware table of Section 1.3, and used for the collision footprint, is the tape measurement of the '
    'built machine, wheel outer to wheel outer. The 375.4 mm marked here is derived from the assembly, '
    'being twice the 157.69 mm half track plus two 30 mm wheel half-widths. The two differ by 15.4 mm, '
    'and the tape figure is the one every experimental result in this report is referenced to.')
fig('loop', 'NEW/fig33_pid_loop.png', 451.0,
    'Figure 7. The per-wheel velocity loop as the deployed firmware runs it. One of these runs for each '
    'of the four wheels, at 100 Hz. The feedforward supplies most of the drive and the proportional-'
    'integral-derivative terms correct only the residual, which is why the integral gain can be as large '
    'as it is without the loop becoming lively. The derivative term acts on the measurement rather than '
    'on the error, so a step in the setpoint produces no derivative kick, and the integral is clamped to '
    'whatever command range is left after the other three terms rather than to a fixed bound.')
fig('ff', 'MEDIA/image8.png', 419.9,
    'Figure 8. The two-term feedforward model fitted against measured open-loop data. The static term '
    'accounts for breakaway friction and the speed-proportional term for the remaining demand. A '
    'single-slope model systematically under-drives the wheels at low speed, which is why the second '
    'term is required.')
fig('track', 'MEDIA/image9.png', 420.0,
    'Figure 9. Closed-loop wheel velocity tracking, wheels free of the ground. Panel (a) is the '
    'front-right wheel over the full 90.8 s run, with the shaded band marking the region expanded in '
    'panel (b). Panel (b) expands the largest commanded step in the run, plotted against time relative '
    'to the step edge with one marker per 20 Hz log sample: the wheel reaches within 5 per cent of the '
    'commanded −2.207 rad/s in 0.20 s, overshoots by 3.5 per cent, and then holds the level to a mean '
    'offset of 0.003 rad/s. Panel (c) gives the tracking error for all four wheels, showing that the '
    'excursions coincide with commanded step edges and not with steady state. The step transient occupies '
    'three to four log samples, which is why it appears in (a) as a vertical edge.')
fig('load', 'MEDIA/image10.png', 419.9,
    'Figure 10. Steady-state drive demand per unit wheel speed, unloaded against loaded. The increase '
    'under chassis weight was predicted to fall between 10 and 30 per cent before the measurement was '
    'made. The measured increases are 22.5, 23.6, 30.3 and 21.0 per cent, a mean of 24: three of the four '
    'motors fall inside the predicted band and the rear-right sits 0.3 points above its upper bound.')
fig('odom', 'MEDIA/image11.png', 419.9,
    'Figure 11. Wheel-odometry trajectories for three logged drives, each driven manually under operator '
    'control, plotted from the recorded pose. In each case the robot was driven back to its starting mark '
    'and the wheel-odometry estimate closed to 19 mm over 8.00 m, 28 mm over 9.61 m and 96 mm over 10.61 '
    'm, which is 0.23, 0.29 and 0.91 per cent of path travelled respectively.')
fig('occl', 'MEDIA/image12.png', 420.0,
    'Figure 12. The self-occlusion sector, re-measured at five independent headings. The mast and payload '
    'block a wedge of approximately 90 degrees, covering 107 of the 430 beams returned per revolution. '
    'Unmasked, these returns are interpreted as an obstacle travelling with the robot.')
fig('cov', 'MEDIA/image13.png', 419.9,
    'Figure 13. Map coverage accumulated under three drive patterns, measured as occupied-cell count '
    'multiplied by the 0.05 m cell size. The quantity is an occupied-cell equivalent length, a proxy for '
    'how much occupancy the map has committed to rather than a physical wall length: a single wall '
    'rendered several cells thick contributes several times its own length, so the totals exceed the '
    'perimeter of the room. Rotation in place contributes almost nothing: a deliberate 714-degree '
    'rotation over 642 s produced 43 occupied cells, 2.1 m on this measure. A 111 s arc combining '
    'rotation with translation produced 1545 cells, 77.2 m, which is 88 per cent of what a full perimeter '
    'drive accumulates in 18 per cent of its duration.')
fig('maps', 'MEDIA/image14.png', 419.9,
    'Figure 14. The three commissioning maps of 15 September, rendered from the saved occupancy grids. '
    'Within the classified regions the recovered wall geometry is consistent across all three runs and '
    'with the layout of the room, and the robot returns to its starting mark in each case. The grey '
    'regions are cells that never accumulated enough observation to be classified, and they are the '
    'criterion that fails on all three. The driven path is visible as a small loop near the origin in each '
    'panel, which is the coverage problem seen directly: the robot cannot classify what it cannot drive past.')
fig('audit', 'MEDIA/image15.png', 484.5,
    'Figure 15. Evidence status of each layer of the system, with the measurement given beside each '
    'entry. The evidence is not all of one kind: closure against the floor is an external reference, the '
    'kinematics and odometry rows are checks against an independent implementation, and the planner, '
    'controller and safety rows are operational demonstrations rather than measurements against a '
    'reference. Three components work but run below their requested update rates. For the five layers that '
    'are not yet established, the entry states the specific reason rather than recording a failure; in '
    'three of those five the reason is the size of the available test area rather than anything on the '
    'platform.')

# ── Chapter 2 ────────────────────────────────────────────────────────
fig('iothw', 'NEW/fig40_iot_hardware.png', 451.0,
    'Figure 16. The appliance and the sensing node as built. Panel (a) is the integrated unit: an '
    'aluminium duct on a stand with the germicidal lamp inside it, the control enclosure mounted on top '
    'near one end, and the 120 mm fan set into the end face. Panel (b) is both control boxes powered and '
    'linked. The enclosure is acrylic, each face a separate panel held on 3D-printed corner standoffs, '
    'with the helical long-range antenna through the top face and the cellular whip on a bulkhead '
    'connector at the side. The two displays are reading live, which is how a node is checked without a '
    'laptop: irradiance and gas state on the left, uptime and firmware build on the right.')
fig('iotarch', 'NEW/fig34_iot_architecture.png', 451.0,
    'Figure 17. The monitoring architecture end to end. Five sensing devices and two actuators sit on one '
    'microcontroller; three communication channels run at the same time rather than as a failover chain; '
    'and a containerised stack on a local server ingests, stores and displays. Each channel has its own '
    'route and they are not interchangeable. Only the Wi-Fi telemetry passes through the message broker. '
    'The long-range radio reaches the database through its own gateway and service. The cellular link is '
    'the only bidirectional one at the human end, carrying alerts out to a handset and accepting commands '
    'back from it, and it is never ingested as telemetry.')
fig('iotlaw', 'NEW/fig39_iot_control_law.png', 451.0,
    'Figure 18. Panel (a) is the actuation law as implemented. The lamp switches on above a gas index of '
    '200 and off below 150, and the fan is ramped rather than switched, starting at half command at the '
    'lamp-on threshold and reaching full command at an index of 500. Panel (b) is what a source-level '
    'audit of the firmware found, listed as defects rather than as features. Every entry was checked '
    'against the code; one claim in earlier circulation, that the fan tachometer never divides by its '
    'sample window, was checked and found to be wrong, and the residual error there is a small high bias '
    'from loop latency.')
fig('iotdash', 'NEW/fig41_iot_dashboard.png', 451.0,
    'Figure 19. The operator dashboard in service, photographed rather than captured. Panel (a) is the '
    'status view for one zone: the gas index reads 143, below the 150 threshold, with the lamp '
    'correspondingly off, while carbon dioxide at the same instant reads 1240 ppm, above its 1200 ppm '
    'alert threshold. That is one consistent operating state, and it shows the deployed logic producing '
    'the configured actuator and alert states for the inputs present at that instant. Panel (b) is the '
    'trend view, whose legends expose the stored tag structure and were used to confirm the database '
    'schema.')

# ── Chapter 3 ────────────────────────────────────────────────────────
fig('fatga', 'SRC/image3.png', 350.0,
    'Figure 20. The proposed framework in one view, reproduced from the research proposal for this '
    'strand. Four contactless modalities feed one edge platform, a fused model produces a single score '
    'per crossing, and the score drives a rest or rotation decision rather than a record. Nothing below '
    'the sensing row exists yet.')
fig('fatdes', 'NEW/fig36_fatigue_design.png', 451.0,
    'Figure 21. The three objectives, and the physical reference each one is measured against. The '
    'right-hand column is the part that makes the strand falsifiable: each modality is checked against '
    'marker-based motion capture or against the contact method it proposes to replace before anything is '
    'fused, and the fused score is then required to beat four single-modality baselines and an ablation '
    'over them. A fused score that cannot beat the best single modality has bought nothing for four '
    'sensors and an edge processor.')

# ── Chapter 4 ────────────────────────────────────────────────────────
fig('road', 'NEW/fig37_three_strand_roadmap.png', 451.0,
    'Figure 22. The three strands across the remaining years. Each is carried on its own until it stands '
    'up by itself, and the convergence sits at the end rather than the beginning, because a strand that '
    'has not been characterised alone contributes nothing measurable to a combined system.')

# the short centred line that sits between a figure and its caption
LABELS = {
    'prior': 'The prior work: chassis variants and the kinematic model',
    'kin': 'Symmetric and non-collinear wheel layouts',
    'plat': 'The machine as built', 'trial': 'The physical platform',
    'elec': 'Deployed electronics', 'geom': 'Asymmetric wheelbase geometry',
    'loop': 'The per-wheel velocity loop', 'ff': 'Feedforward model',
    'track': 'Closed-loop tracking', 'load': 'Ground load',
    'odom': 'Endpoint closure', 'occl': 'Self-occlusion',
    'cov': 'Rotation and mapping coverage', 'maps': 'Commissioning maps',
    'audit': 'System validation status',
    'iothw': 'The appliance and the sensing node',
    'iotarch': 'Monitoring and control architecture',
    'iotlaw': 'The control law, and what a source audit of it found',
    'iotdash': 'The operator dashboard in service',
    'fatga': 'The proposed framework',
    'fatdes': 'Objectives and the references they are measured against',
    'road': 'The three strands across the remaining years',
}

ABSTRACT = [
    "This report covers the first year of a doctoral project that runs three strands at once: a robot "
    "that can work inside a narrow storage aisle, an instrumented environmental monitoring system for "
    "the space that robot moves through, and a proposed method for assessing the physical fatigue of "
    "the people who share that space, without asking any of them to wear anything.",

    "The first strand is the substantial one, and most of this report is about it. A storage aisle is "
    "sized for the goods it holds and for a human picker, so a vehicle working there has centimetres of "
    "clearance rather than metres. Earlier work in this laboratory derived the kinematics for an "
    "asymmetric, non-collinear mecanum wheel layout intended for exactly that constraint, and "
    "demonstrated the principle on a small prototype. This year took that geometry to a full-scale "
    "machine of 45.54 kg, built the closed-loop velocity control it needs at every wheel, and measured "
    "what the result actually does. Four results are established against physical references rather "
    "than asserted: the velocity controller tracks to 0.040 to 0.047 rad/s root-mean-square with the "
    "wheels free and 0.066 to 0.074 under chassis weight, with no channel saturating in any recorded "
    "run; the kinematic and odometry implementations agree with an independent reference to machine "
    "precision across twenty thousand generated cases; wheel-odometry endpoint closure stays below 1 per "
    "cent of path travelled out to about 10 m; and a scan-matching front end was measured to increase "
    "pose error rather than reduce it, most sharply on a drive where the same wheels and the same scans "
    "gave 16.2 mm unmatched and 206.7 mm matched. Autonomous point-to-point navigation has been "
    "demonstrated, though within a live mapping session rather than against a saved map.",

    "The second strand is a multi-parameter monitoring and control system, built from nothing over the "
    "same period and now deployed across four zones in two radio-isolated installations sharing one "
    "database. It drives an ultraviolet lamp and a fan from measured air condition rather than from a "
    "timer, reports over three wireless channels that run concurrently rather than as a failover chain, "
    "and recovers from a power interruption without anyone attending to it.",

    "The third strand is, at this stage, a hypothesis and a completed literature survey. No hardware has "
    "been built and no data collected. It is carried here because the argument for it is already "
    "specific: the contact-based methods work well and are unusable on an operating floor for reasons "
    "that are practical rather than evidential, and the contactless modalities that might replace them "
    "have each been characterised alone but never fused for whole-body physical fatigue in an "
    "uncontrolled industrial setting.",

    "Three things remain unresolved at the end of the year, and the reasons differ. A commissioning map "
    "meeting all four acceptance criteria is blocked by the size of the available test area rather than "
    "by anything on the platform. The effect of the asymmetric geometry itself is unquantified, because "
    "no matched symmetric baseline has been built. And several degrees of heading error survive every "
    "instrument currently fitted, narrowed to either an encoder or wheel-radius scale error or a rigid "
    "all-wheel slip mode, which cannot be separated without an angular-rate measurement that does not "
    "come from the wheels.",
]

# ── the body ──────────────────────────────────────────────────────────
# ('h1', t)  chapter    ('h2', t)  section     ('p', t)  new paragraph
# ('lead', bold, rest)  paragraph with a bold lead-in
# ('R', n)   reuse paragraph n of the September document verbatim
# ('Rs', n, [(find, repl), ...])  reuse with asserted substitutions
# ('F', key) figure, its label line and its caption
# ('T', name) table      ('E', name) equation


BODY = [
    # ══════════════════════════════════════════════════ INTRODUCTION ══
    ('h1', 'Introduction'),
    ('R', 62),
    ('p',
     'Three separate problems live in that same corridor, and this project takes all three. The first is '
     'motion: getting a machine down the aisle and back without touching anything, and knowing where it '
     'is well enough to do that without a person driving it. The second is the condition of the space '
     'itself, which is where the goods sit and where the air is least controlled. The third is the '
     'people, who walk that aisle under load for a full shift in conditions that, in Indian facilities, '
     'are often well outside anything comfortable.'),
    ('p',
     'They are treated here as three strands of one problem rather than three projects, and the reason '
     'is not that they share a theme. It is that they share instrumentation. Multi-sensor integration, '
     'calibration against a physical reference, real-time acquisition, and closed-loop control with '
     'interlocks that fail safe are the same engineering in all three, and a mistake made in one strand '
     'shows up as a lesson in the next. The monitoring system taught the robot work how to verify a '
     'configuration against a running system rather than against a file. The robot work taught the '
     'monitoring system that a control law has to be measured responding to a change, not inferred from '
     'a consistent snapshot.'),
    ('p',
     'There is a longer-range reason as well. A robot that already traverses every aisle is the obvious '
     'carrier for the sensing the second strand does from fixed points, and a facility that knows its '
     'own air condition and its own traffic is most of the way to knowing how hard its people are '
     'working. That convergence is the fourth-year ambition rather than a claim about this year, and it '
     'is deliberately placed at the end of the plan. A strand that has not been characterised on its own '
     'contributes nothing measurable to a combined system, so each one is carried until it stands up by '
     'itself.'),
    ('p',
     'The three are at very different stages, and the report does not pretend otherwise. The robot is '
     'built, instrumented and measured, and Chapter 1 is correspondingly long. The monitoring system is '
     'deployed and running, and Chapter 2 describes it without the same depth of characterisation, '
     'because it has not had the same depth of measurement. The fatigue strand is a hypothesis and a '
     'literature survey, and Chapter 3 says so in its first paragraph rather than dressing the position '
     'up. Chapter 4 sets out what the remaining years do with all three.'),

    ('h2', 'Motivation'),
    ('R', 63),
    ('R', 64),
    ('R', 65),
    ('Rs', 98, [('Earlier work in this laboratory derived the kinematics for an asymmetric, non-collinear '
                 'mecanum layout intended for narrow aisles and demonstrated the principle on a prototype [1].',
                 'Earlier work in this laboratory derived the kinematics for an asymmetric, non-collinear '
                 'mecanum layout intended for narrow aisles and demonstrated the principle on a prototype [1], '
                 'and Section 1.2 sets out what that transformation is.')]),
    ('R', 99),
    ('R', 100),
    ('p',
     'Both of those supporting strands answer a question the first one raises but cannot settle. A robot '
     'that surveys an environment is only as useful as the measurement it carries, and a measurement '
     'that has never been calibrated against anything is not a measurement. A machine sharing an aisle '
     'with people ought to know something about the state those people are in. Neither question needs '
     'the robot to exist first, which is why both strands were started in parallel rather than queued '
     'behind it.'),

    ('h2', 'Objectives'),
    ('lead', 'Objective 1: Development and experimental characterisation of a full-scale asymmetric '
             'mecanum platform for narrow-aisle operation.', ''),
    ('R', 103),
    ('lead', 'Objective 2: Localisation and autonomous navigation at corridor-width clearances.', ''),
    ('R', 105),
    ('lead', 'Objective 3: Quantification of the cost and benefit of the asymmetric wheel layout.', ''),
    ('R', 107),
    ('lead', 'Objective 4: An instrumented, closed-loop environmental monitoring system for warehouse '
             'environments.', ''),
    ('R', 109),
    ('lead', 'Objective 5: A contactless framework for assessing worker fatigue.', ''),
    ('R', 111),

    # ═════════════════════════════════════════════════════ CHAPTER 1 ══
    ('h1', 'Chapter 1  The Narrow-Aisle Robot'),
    ('h2', '1.1 Motivation'),
    ('p',
     'The aisle is where inventory is counted, where goods are picked and replaced, and where the '
     'environment is least controlled. It is also precisely the space in which conventional mobile '
     'platforms are hardest to deploy, which is why current warehouse automation largely works around it '
     'rather than in it. A machine that holds its lateral position in a sub-metre corridor, carries a '
     'useful load, and knows where it is well enough to navigate without an operator would make several '
     'distinct warehouse tasks automatable on one platform: inventory scanning, environmental survey, '
     'surface disinfection, and cargo transfer between a rack and a pick point.'),
    ('p',
     'The geometric premise for such a machine already exists, and it was established here. What the '
     'prior work did not establish is whether the geometry survives the transition to a full-scale '
     'machine. A prototype demonstrates that the transformation between wheel and body velocity is '
     'correct. It does not show that four geared motors driving a 45.54 kg machine will track commanded '
     'velocities accurately, that the resulting pose estimate will be good enough to navigate on, or '
     'that a perception stack can be built on top of it without the asymmetry causing trouble somewhere '
     'unexpected. Those questions need a built machine, closed-loop control at every wheel, and '
     'measurement against something physical.'),
    ('p',
     'That is what this chapter reports: the platform as built, the control and perception layers put on '
     'top of it, and what each of those layers was measured to do. The order runs from what the machine '
     'is, through how it was made to work, to what it was found to do, and ends with an honest statement '
     'of which layers are established and which are not.'),

    ('h2', '1.2 Review of Literature'),
    ('R', 68),
    ('p',
     'The transformation itself is worth setting out, because everything downstream depends on it and '
     'because the difference from the symmetric case is small enough to be missed. On a symmetric '
     'platform the four wheels sit at the corners of a rectangle, every wheel is the same longitudinal '
     'distance from the body centre, and one yaw coefficient serves all four. Move one diagonal pair '
     'inward and that is no longer true. The outer pair keeps a lever arm of the outer longitudinal '
     'distance plus the half track, the inner pair gets a shorter one, and the two differ here by 14 per '
     'cent. Figure 1 is that paper\u2019s own drawing of the two chassis variants and its kinematic schematic, and Figure 2 puts the symmetric and the non-collinear layouts side by side with the transformation each implies, at the dimensions of the machine built here. The '
     'translation terms are identical in both, which is why forward and lateral motion feel the same on '
     'either machine; only the yaw column changes. That is the whole of the difference, and it is also '
     'the whole of the risk, because a wheel driven with the wrong lever arm produces a yaw rate wrong '
     'by that 14 per cent and nothing else in the transformation gives any sign of it.'),
    ('F', 'prior'),
    ('F', 'kin'),
    ('R', 69),
    ('R', 70),
    ('R', 71),
    ('R', 72),

    ('h2', '1.3 The platform and its starting condition'),
    ('F', 'plat'),
    ('F', 'trial'),
    ('R', 121),
    ('p',
     'Figures 3 and 4 show the machine as it stands. The second is worth a moment of attention. Panel '
     '(a) carries the body-axis convention used throughout this report, and panels (c) and (d) are the '
     'start and end frames of the drive that established which way the scanner counts its angles. That '
     'is the sort of thing that looks trivial once it is fixed and is expensive for as long as it is '
     'not.'),
    ('R', 122),
    ('T', 'TABLE_SPEC'),

    ('h2', '1.4 The drive controller and the encoder return path'),
    ('R', 125),
    ('R', 126),
    ('R', 127),
    ('R', 129),
    ('R', 130),
    ('R', 131),
    ('p',
     'Figure 5 traces the result end to end in three layers: power distribution from the battery up to '
     'the 24 V drive rail and down to the 5 V logic rail, compute and command, and drive with its '
     'odometry return. The encoder rows carry their wire colours, because the front and rear motors do '
     'not share a convention and that difference has already put a channel on the wrong pin once during '
     'commissioning.'),
    ('F', 'elec'),

    ('h2', '1.5 Kinematic model'),
    ('F', 'geom'),
    ('R', 139),
    ('p', 'Figure 6 gives those distances as they were taken off the mechanical assembly.'),
    ('E', 'EQ1'),
    ('R', 141),
    ('E', 'EQ2'),
    ('R', 144),
    ('R', 145),
    ('E', 'EQ3'),
    ('R', 147),
    ('R', 148),
    ('E', 'EQ4'),
    ('R', 150),
]

BODY += [
    ('h2', '1.6 Wheel-level velocity control, and where the gains came from'),
    ('p',
     'Velocity control runs on the ESP32 at 100 Hz, one independent loop for each of the four wheels, '
     'and Figure 7 shows the structure of a single one. The loop is not a plain proportional-integral-'
     'derivative controller, and the distinction matters for everything that follows: a two-term '
     'feedforward model supplies most of the drive from the commanded velocity alone, and the '
     'three feedback terms correct only what the feedforward gets wrong. That split is what lets the '
     'integral gain be as large as it is without the loop becoming lively.'),
    ('p',
     'The feedforward came first, because it was the part that could be fitted to data rather than '
     'tuned by hand. Its form is a speed-proportional term plus a static term carrying the sign of the '
     'command. The speed-proportional coefficient sits between 37.3 and 38.4 drive counts per rad/s '
     'across the four motors, a spread of 3 per cent, and the static term is 8 counts on all four. Both '
     'were fitted against three independent open-loop campaigns rather than one: a manual drive logged '
     'at steady state, an automated test sweeping demand in 1.5 s windows, and a back-calculation from '
     'an earlier closed-loop run. The reason a single-slope model will not do is visible in the data '
     'before any fitting: the ratio of drive command to resulting wheel speed rises as speed falls, '
     'which is the signature of a breakaway friction term that a straight line through the origin '
     'cannot reproduce. The two-term fit reproduces every measured point to within about 6 per cent, '
     'and Figure 8 shows it against the measurements. The static term is faded in across 0.05 to 0.20 '
     'rad/s rather than applied as a step at any non-zero command, so that a very small commanded '
     'velocity does not produce a discontinuity in the drive.'),
    ('F', 'loop'),
    ('F', 'ff'),
    ('p',
     'With the feedforward fitted, the plant is characterised well enough to compute the feedback gains '
     'rather than search for them. Inverting the fitted slope gives a plant gain of about 0.0263 rad/s '
     'per drive count. For a first-order plant, direct synthesis fixes the integral gain from that '
     'number and a chosen closed-loop time constant alone: the integral gain is the reciprocal of their '
     'product. A closed-loop time constant of 0.15 s was chosen, which is fifteen control periods and '
     'deliberately conservative, and it gives an integral gain of 253. The deployed value is 250.'),
    ('p',
     'That gain is the single largest change from the previous firmware, where it was 30. At 30 the '
     'integral moved roughly three drive counts per second, which against a feedforward error of any '
     'size is far too slow to be doing useful work: an air run in May settled in up to 3.79 s, and what '
     'was settling it was mostly the proportional term. Raising it by a factor of eight is a large '
     'change to make at once, and it was only safe because of the feedforward. When the feedforward '
     'carries the bulk of the command, the integral is correcting a small residual rather than supplying '
     'drive from zero, so a gain that would be reckless on a bare loop is appropriate here.'),
    ('p',
     'The proportional gain is the one number in the loop that is an estimate rather than a fit, and it '
     'is worth saying so plainly. Direct synthesis sets it as the product of the integral gain and the '
     'plant time constant, and that time constant had never been measured on this machine, because every '
     'bench run to that point had logged steady-state points and no transients. A value of 0.18 s was '
     'assumed, on the grounds that it is plausible for a 100 W motor behind a 47:1 planetary gearbox, '
     'and it gives a proportional gain of 45. The assumption was later tested. Plant identification put '
     'the real time constant at about 0.09 s, half what had been assumed, which by the same formula '
     'would call for a proportional gain of roughly 22. Two recomputed gains were then run against the '
     'gain already in service, across sixteen combinations of setpoint and motor, and both produced more '
     'overshoot. The original value was kept, on measured evidence rather than on the theory that '
     'produced it. This is the least satisfying part of the tuning and it is recorded as such: the '
     'deployed gain is right, but the argument that originally justified it turned out to rest on a '
     'number that was wrong by a factor of two.'),
    ('p',
     'The derivative gain is 0.5, which is small on purpose. Against a genuinely first-order plant a '
     'matched proportional-integral pair needs no derivative action at all, and everything this term is '
     'doing is damping lag that the first-order model does not contain: driver delay, compliance in the '
     'gearbox, and the velocity filter itself. Two details of how it is applied matter more than its '
     'size. It acts on the measurement rather than on the error, so a step in the commanded velocity '
     'produces no derivative kick, and it is taken through a heavier filter than the velocity signal, '
     'because differentiating amplifies whatever noise survives the first filter.'),
    ('p',
     'Three arrangements around the loop do more for its behaviour than the gains do. The integral is '
     'clamped dynamically, to whatever command range is left after the feedforward and the proportional '
     'and derivative terms have taken their share, rather than to a fixed bound; the previous firmware '
     'used a fixed clamp, which in combination with the low integral gain of the time allowed the '
     'integral state to reach values it could never usefully act on. The commanded velocity is passed '
     'through a slew limit of 12 rad/s squared before the loop sees it, so that a step command from the '
     'host cannot ask for an acceleration the hardware will not produce, which is the condition that '
     'drives an integrator into saturation in the first place. And the minimum drive output was lowered '
     'from 15 counts to 5. The larger value had been there to suppress audible hum, but it cut a dead '
     'zone straight through the middle of the range in which the controller does its fine regulation, '
     'and produced a limit cycle at low speed; with breakaway friction now handled properly by the '
     'static feedforward term, the threshold can sit at the level where the motor is genuinely silent.'),
    ('p',
     'Two limits bound what the loop is allowed to do. The velocity ceiling is 5.20 rad/s per wheel, '
     'chosen so that the worst of the four motors needs about 208 of the 255 available drive counts at '
     'that speed, leaving roughly 18 per cent of the range as authority for the feedback terms. That '
     'margin is an in-air figure and the ground measurement of Section 1.10 is the reason it has to be '
     'revisited. Separately, three trips watch every wheel: overspeed, stall, and a runaway detector '
     'that looks for a saturated command pushing one way while the wheel turns the other and does not '
     'slow down. The last of those exists for a specific failure. The drive direction sign and the '
     'encoder direction sign have to agree for each motor; if they disagree the loop sees positive '
     'feedback, and because a motor rated at 60 rpm cannot physically overspeed its way past the '
     'overspeed threshold, nothing else in the system would catch it.'),
]


BODY += [
    ('h2', '1.7 Control architecture and software integration'),
    ('R', 153),
    ('R', 154),
    ('R', 155),
    ('R', 156),

    ('h2', '1.8 Perception, mapping and navigation'),
    ('R', 158),
    ('R', 159),
    ('R', 160),
    ('R', 162),
    ('R', 163),
    ('R', 164),

    ('h2', '1.9 Analysis method'),
    ('R', 176),
    ('R', 177),

    ('h2', '1.10 Results: closed-loop velocity control'),
    ('p',
     'Figure 9 shows what the loop does to a commanded step with the wheels off the ground, and Figure 10 '
     'shows what happens to the steady-state demand when the chassis weight goes back on.'),
    ('F', 'track'),
    ('R', 187),
    ('T', 'TABLE_WHEEL'),
    ('R', 189),
    ('R', 190),
    ('F', 'load'),
    ('R', 195),

    ('h2', '1.11 Results: kinematics and motion estimation'),
    ('R', 197),
    ('R', 198),
    ('R', 199),
    ('F', 'odom'),
    ('R', 203),
    ('R', 204),
    ('R', 205),

    ('h2', '1.12 Results: perception'),
    ('p',
     'Two perception results are reported, and they are of different kinds. Figure 12 is a property of '
     'the machine: the mast sits in the scan plane, so the robot blocks part of its own sweep, and the '
     'sector was measured at five independent headings rather than assumed from the geometry. Figure 13 '
     'is a property of how the robot is driven rather than of what the scanner can see, and it turned '
     'out to matter more.'),
    ('F', 'occl'),
    ('R', 210),
    ('F', 'cov'),
    ('R', 214),

    ('h2', '1.13 Results: mapping, and the constraint imposed by the available workspace'),
    ('F', 'maps'),
    ('R', 219),
    ('R', 220),
    ('R', 221),
    ('R', 222),
    ('R', 223),
    ('R', 224),
    ('R', 225),
    ('R', 226),
    ('T', 'TABLE_SCAN'),
    ('R', 228),
    ('R', 229),
    ('R', 230),
    ('R', 231),
    ('R', 232),
    ('R', 233),
    ('R', 234),

    ('h2', '1.14 Results: autonomous navigation'),
    ('R', 236),
    ('R', 237),
    ('R', 238),

    ('h2', '1.15 Operating without an inertial sensor'),
    ('R', 240),
    ('R', 241),
    ('R', 242),
    ('R', 243),
    ('R', 244),

    ('h2', '1.16 Present state of the platform'),
    ('F', 'audit'),
    ('R', 249),
    ('R', 250),
    ('R', 251),
    ('R', 252),
    ('R', 253),
    ('R', 254),

    ('h2', '1.17 Conclusions on the robot'),
    ('p',
     'The asymmetric geometry survives the move to full scale. That is the headline, and it is worth '
     'stating in the form the evidence supports rather than in the form the project would prefer: no '
     'asymmetry-specific penalty has been detected in any experiment performed. The transformation is '
     'implemented correctly to the limit of double precision, tracking is clean on every axis including '
     'the lateral and rotational ones, endpoint closure holds below 1 per cent of path out to 10.61 m, '
     'and no yaw-consistency residual above the episode threshold has appeared. An absence of penalty '
     'across a year of measurement is not the same thing as a measured cost of zero, and Objective 3 is '
     'not closed until a matched symmetric baseline exists to compare against.'),
    ('p',
     'Below the map, the platform is characterised. The motors track to a known error in both the '
     'unloaded and loaded conditions, the encoder path is clean after the level-translation work of '
     'Section 1.4, the feedforward is fitted rather than guessed, and the kinematic and odometry '
     'implementations have been checked against an independent reference rather than against '
     'themselves. At and above the map, three layers are not established, and in each case the reason '
     'is specific. Mapping produces consistent and repeatable geometry but cannot meet a coverage '
     'criterion in a room this size. Localisation against a saved map has never been run, because there '
     'is no accepted map to run it against. And a scan-matching front end, measured rather than assumed, '
     'made the pose estimate worse on all three routes it was tested on, so it is switched off.'),
    ('p',
     'The two constraints those shortfalls resolve to are worth separating, because only one of them is '
     'about the robot. The first is the size of the available test area, which is an environmental '
     'constraint and the binding one. The second is the deliberate absence of an inertial sensor, which '
     'is a decision rather than an omission, and which is what made the unfused behaviour of the wheel '
     'estimate visible in the first place. Both are addressed directly in Chapter 4.'),
]


# A replacement for the previous document's monitoring table, which described
# the system in generic terms. The parts are now named.
TABLE_IOT2 = {
    'cols': [132.0, 322.0],
    'head': ['Item', 'Specification'],
    'rows': [
        ['Sensing node', 'Arduino UNO R4 WiFi, Renesas RA4M1 core'],
        ['Carbon dioxide, temperature, humidity',
         'Sensirion SCD40 on the serial bus, 400 to 5000 ppm'],
        ['Particulate matter', 'MPM10-AS optical counter on the same bus, PM2.5 and PM10'],
        ['Gas', 'MQ-135 metal-oxide module, an index of 0 to 500 on an analogue '
                'channel with a separate digital threshold flag'],
        ['Ultraviolet irradiance', 'GUVA-S12SD photodiode, 240 to 370 nm, on a second analogue channel'],
        ['Local display', 'LCD1602 over the serial bus, eight rotating status screens'],
        ['Actuators', 'Opto-isolated relay switching the lamp mains, and a 120 mm '
                      'four-wire fan with tachometer feedback'],
        ['Radios on the node', 'Wi-Fi, a RYLR998 long-range module, and a Quectel '
                               'EC200U cellular modem'],
        ['Gateway', 'A second microcontroller carrying another RYLR998, '
                    'level-translated into the server’s serial port'],
        ['Server', 'Raspberry Pi 5 running a message broker, a flow engine, a '
                   'time-series database, a dashboard server and a control service '
                   'in containers, with the radio ingestion service alongside them'],
        ['Channels', 'Wi-Fi every 5 s, long-range radio every 30 s at no more than '
                     '240 bytes, cellular messaging on alert and every 30 min'],
        ['Control law', 'Lamp on above a gas index of 200 and off below 150; fan '
                        'ramped from half to full command across an index of 200 to 500'],
        ['Alert thresholds', '38 °C, 1200 ppm carbon dioxide, gas index 200, '
                             '55 µg/m³ PM2.5'],
        ['Power', 'Two isolated 12 V supplies brought to a single common ground point'],
        ['Zones', 'Four, across two radio-isolated deployments against one database'],
    ],
}

BODY += [
    # ═════════════════════════════════════════════════════ CHAPTER 2 ══
    ('h1', 'Chapter 2  Environmental Monitoring for the Warehouse Space'),
    ('h2', '2.1 Motivation'),
    ('R', 76),
    ('R', 77),
    ('p',
     'There is a narrower version of the same argument, and it is the one the system was actually built '
     'against. Continuous monitoring in a laboratory or a store room is usually done one of two ways: '
     'with proprietary instruments that are expensive and will not be told what to do, or by somebody '
     'writing readings down, which introduces transcription error and leaves a gap whenever nobody is '
     'there. An air-treatment appliance adds a second requirement on top of that. It has to act on what '
     'it measures, and somebody has to be able to confirm that the action had an effect. A treatment '
     'duct running on a timer offers neither. It cannot raise airflow when the air is dirty, and it '
     'cannot tell anyone when its lamp has failed.'),
    ('R', 78),

    ('h2', '2.2 Review of Literature'),
    ('R', 80),
    ('R', 81),
    ('R', 82),

    ('h2', '2.3 The unit, the enclosure and the sensors'),
    ('p',
     'The system instruments a closed air-treatment chamber. Air is drawn through an aluminium duct by a '
     'fan set into its end face, passes a germicidal lamp, and leaves at the other end. The sensing and '
     'control enclosure is mounted on top of the duct near one end, so the electronics sit outside the '
     'treated path and the only things inside it are the lamp and the airflow. Figure 16 shows the '
     'integrated unit and the node.'),
    ('F', 'iothw'),
    ('p',
     'The enclosure is worth a sentence because it was designed rather than bought. It is acrylic, with '
     'each face a separate panel held by 3D-printed corner standoffs and slotted machine screws, so any '
     'one face can come off without disturbing the others. The helical long-range antenna passes through '
     'the top panel and the cellular whip mounts externally on a side panel through a bulkhead '
     'connector. Two barrel jacks and a single cable egress complete the penetrations, and two runs '
     'leave through that egress: switched mains to the lamp, and the four-conductor fan line carrying '
     'supply, ground, speed command and tachometer return. One correction worth recording, because '
     'earlier project documents have it wrong and a drawing traced from those documents would be wrong '
     'too: the enclosure is not a cube. The photographs show a box visibly wider than it is deep.'),
    ('p',
     'Five sensing devices and two actuators sit on one microcontroller. Carbon dioxide, temperature and '
     'relative humidity come from a single photoacoustic part, which gives all three from one device and '
     'one calibration. Particulate mass at two size fractions comes from an optical counter on the same '
     'serial bus. A metal-oxide sensor supplies a general reducing-gas index on an analogue channel, '
     'with a separate digital line that trips at a hardware threshold, and an ultraviolet photodiode on a '
     'second analogue channel reads irradiance in the duct. A character display on the same serial bus '
     'cycles through eight status screens, which is how a node is checked in the laboratory without '
     'attaching a computer to it. The table below lists the parts.'),
    ('p',
     'The two actuators are driven differently and for different reasons. The lamp runs from mains and '
     'is switched through an opto-isolated relay, so there is no electrical path between the mains side '
     'and the logic. The fan is a four-wire part driven by a pulse-width command with its tachometer '
     'line read back, which makes it the one actuator in the system whose response can be confirmed '
     'rather than assumed. Power is deliberately split into two isolated supplies brought to a single '
     'common ground point, and that split is not an elegance. The cellular modem draws roughly 2 A in '
     'transmit bursts, and sharing a rail with the microcontroller produced brownout resets that looked '
     'exactly like firmware crashes. Any rebuild that merges the rails will reproduce that fault.'),
    ('p',
     'One measurement channel does not do what the system design assumes, and it is recorded here rather '
     'than left for a reader to discover. Ultraviolet irradiance is reported in milliwatts per square '
     'centimetre, but the responsivity coefficient that would convert the photodiode voltage into that '
     'unit is still set to one. The number is a voltage with a unit written after it. The sensor is '
     'fitted, it reads, and its value reaches the display and both telemetry payloads, but it appears in '
     'no control path and no alert path, which means the loop described in some project documents as '
     'taking two inputs in fact takes one. Correcting it needs a reference radiometer and a fixed '
     'measurement geometry, neither of which is difficult, and it is listed in Chapter 4.'),
    ('T', 'TABLE_IOT'),

    ('h2', '2.4 The communication architecture'),
    ('p',
     'Telemetry leaves the node by three routes at once. Local Wi-Fi carries a full message every five '
     'seconds to a broker on the server, where a flow engine ingests it and writes it to the time-series '
     'database. A long-range radio sends an abbreviated packet of at most 240 bytes every thirty seconds '
     'to a second microcontroller acting as a gateway, and a dedicated service on the server reads that '
     'gateway over a serial link and writes to the same database with the same schema, distinguished '
     'only by a source tag. A cellular modem sends a short message on any threshold breach, on the '
     'corresponding clear, and as a summary every thirty minutes. Figure 17 traces all three.'),
    ('F', 'iotarch'),
    ('p',
     'Those three are not variants of one path, and the figure is drawn to make the difference visible '
     'because the distinction decides what survives a failure. Only the Wi-Fi telemetry passes through '
     'the message broker. The radio path never touches it, because the gateway speaks a framed serial '
     'protocol rather than a publish-subscribe one and its service writes to the database directly. And '
     'the cellular path is not ingested at all: it delivers a message to a person, and nothing on the '
     'server records it. A reader who assumes all three converge on the broker would draw the wrong '
     'conclusion about what a server outage costs.'),
    ('p',
     'The cellular channel is also the only one that is bidirectional at the human end. The node accepts '
     'the same command vocabulary on every channel, including short messages from a handset, so an '
     'operator with no network access can still ask a node for a snapshot or switch its lamp. Commands '
     'from the dashboard travel one of two ways, selected at runtime by a variable read from the browser '
     'address rather than by a firmware change: through the flow engine and the broker when the node is '
     'inside Wi-Fi coverage, or through the control service and out by radio when it is not. That is what '
     'lets a zone move in and out of coverage without anything being reflashed.'),
    ('R', 174),
    ('p',
     'Two properties of the radio layer should be stated rather than implied. Separation between the two '
     'co-located deployments is by network identifier, which the transceiver filters at the protocol '
     'layer, so the two operate without physical frequency separation. That is a documented vendor '
     'feature rather than a contribution of this work, and it is an addressing filter rather than a '
     'security mechanism: the control path carries no message authentication, so any transmitter within '
     'range configured to the right identifier can actuate a lamp. That is acceptable on an isolated '
     'laboratory network and is not acceptable anywhere else. Separately, the two deployments were '
     'configured on different frequencies, and neither matches the delicensed band available in India. '
     'The link works and the deployment is a bench one, so this has obstructed nothing, but it would have '
     'to be settled before the system went near a real facility.'),

    ('h2', '2.5 The control law and the operator dashboard'),
    ('p',
     'Actuation is driven from the gas index with hysteresis and a dead band, and Figure 18 shows the law '
     'as implemented alongside what an audit of the firmware that implements it found. The lamp switches '
     'on when the index rises above 200 and off when it falls below 150, so the two thresholds are '
     'separated by a band in which nothing changes and the relay cannot chatter around a single '
     'setpoint. The fan is not switched but ramped, from half command at the lamp-on threshold to full '
     'command at an index of 500, and it is never driven below half duty while the lamp is energised, on '
     'the reasoning that irradiating stationary air accomplishes little.'),
    ('F', 'iotlaw'),
    ('p',
     'The index driving all of this is a rescaled analogue count rather than a concentration. A '
     'calibration routine for that sensor runs at first boot, computes a value, stores it, and the '
     'control law never reads it. As a control input the raw index is adequate, since the thresholds '
     'were set against it and it moves in the right direction when the air worsens. As a reported '
     'quantity it is not, and no number derived from it should be quoted as a concentration in any '
     'publication.'),
    ('p',
     'The alert path is separate from the control path and is not built the same way. A breach fires '
     'simultaneously on all three channels, a clearing message follows on the same three, and the alert '
     'state is latched so that a sustained breach does not generate a message on every cycle. '
     'Particulate matter is evaluated only when the reading is valid, so a failed sensor never raises a '
     'false alarm, and a sensor that fails to respond is transmitted as a negative marker rather than as '
     'zero, which keeps a broken particulate sensor distinguishable from genuinely clean air. What the '
     'alert path does not have is the dead band that the control path does. It compares a noisy signal '
     'against a bare threshold, so a reading sitting near a limit flaps, and each transition sends a '
     'message. Figure 19 happens to catch the system 40 ppm above the carbon dioxide threshold, which is '
     'well inside that flapping range.'),
    ('F', 'iotdash'),
    ('p',
     'The operator sees the system through a dashboard served from the local server, twenty-three panels '
     'templated per zone so that one layout serves all four installations. Alongside the readings it '
     'carries in-panel actuator control, and this is where the most interesting defect lives. An '
     'operator command to switch the lamp or the fan off actuates correctly and then does not clear '
     'automatic mode, so the closed loop reverts it on its next pass. The on-commands do clear it. Off is '
     'precisely the command an operator issues when they want the machine to stop doing what it is '
     'doing, and it is the one that does not hold.'),

    ('h2', '2.6 What is deployed, and what it does not yet establish'),
    ('R', 256),
    ('R', 257),
    ('p',
     'Two limitations are recorded plainly rather than left in a defect register. The gas index that '
     'drives the present control law is a relative signal rather than a calibrated concentration, '
     'adequate for actuation and trend observation and not defensible in any quantitative claim. And '
     'lamp-failure detection, which is the capability that would distinguish this unit from a timer, is '
     'not implemented. The irradiance measurement that would support it is taken, displayed and '
     'transmitted; nothing acts on it. A dead lamp currently raises nothing. Both are identified with '
     'the specific code paths involved in the project record for that system, and both are in Chapter 4.'),
    ('p',
     'One finding from the same audit is worth reporting because it affects timing rather than accuracy '
     'and because it explains several symptoms at once. The cellular inbox poll waits a fixed five '
     'seconds on every call and is invoked every ten, so a node with a working modem spends roughly half '
     'its wall-clock time inside that loop. That is the underlying cause of publish intervals jittering '
     'between five and ten seconds and of dashboard commands taking up to five seconds to act. It is '
     'about six lines to fix and is the single highest-value change available in that firmware.'),

    ('h2', '2.7 Towards warehouse management'),
    ('R', 267),
    ('p',
     'The architecture is already shaped for the wider application. Zones are templated rather than '
     'hand-built, the database takes one schema regardless of which transport the data arrived on, and '
     'adding an installation means adding a node and a zone identifier rather than rebuilding anything; '
     'retargeting a gateway is three constants, and retargeting its service is four values in a '
     'configuration file. A facility instrumented this way would know the condition of every storage area '
     'continuously rather than by inspection, and would drive treatment from that condition rather than '
     'from a timetable.'),
    ('p',
     'The step that makes it more than a set of fixed instruments is the one that needs the other strand. '
     'Fixed nodes measure the places they are bolted to, and a warehouse has far more places than anyone '
     'will instrument. A robot that already traverses every aisle, carrying the same sensor complement, '
     'samples the spaces between the fixed nodes and reports into the same database on the same schema. '
     'That turns a handful of point measurements into something closer to a survey. It needs the '
     'navigation layer of Chapter 1 finished first, which is why it sits where it does in the plan of '
     'Chapter 4 rather than being attempted now.'),
]

BODY += [
    # ═════════════════════════════════════════════════════ CHAPTER 3 ══
    ('h1', 'Chapter 3  Contactless Assessment of Worker Fatigue'),
    ('h2', '3.1 The problem, and the goal'),
    ('p',
     'This chapter is short, and the reason is that the work it describes has not been done. The strand '
     'consists of a hypothesis, a completed literature survey and a research proposal built on them. No '
     'hardware has been built, no data has been collected, and nothing has been measured. It is carried '
     'in this report because the argument is already specific enough to state, to criticise and to test, '
     'and because the first year of a doctorate is the right time to establish whether a direction is '
     'worth the next three.'),
    ('p',
     'The setting is the third thing in the aisle. India’s logistics and warehousing sector employs '
     'over 22 million people, is expanding under the National Logistics Policy of 2022, and records more '
     'than 26,800 workplace incidents a year. Nearly 70 per cent of that workforce is in the unorganised '
     'sector, where occupational health protocols are minimal or absent. The conditions make fatigue '
     'worse rather than merely present: shifts of ten to twelve hours, sustained walking and lifting, '
     'and ambient temperatures that routinely exceed 40 °C. Occupational heat stress in Indian '
     'workplaces has been measured directly, with documented exceedances of established thresholds and '
     'associated health and productivity consequences [23], and comparable findings are reported across '
     'steel [24], construction [25] and multi-sector southern-Indian settings [26].'),
    ('R', 87),
    ('p',
     'The goal, stated at its largest, is a warehouse that can tell how hard the people in it are '
     'working without asking any of them to wear anything, and can do it continuously rather than at a '
     'shift review. The hypothesis underneath it is more specific than that, and it is what makes the '
     'strand testable. Physical fatigue is proposed to show itself as a correlated signature across '
     'several physiological domains at once: gait regularity deteriorating, heart and respiration rates '
     'rising, and facial skin temperature climbing. If that is right, then a system watching all of those '
     'at the same time should beat any system watching one of them, and it should beat it hardest under '
     'exactly the conditions where single modalities struggle, which are occlusion, heat and an '
     'uncontrolled floor.'),

    ('h2', '3.2 Review of Literature'),
    ('p',
     'Fatigue detection as currently practised falls into three categories, and each fails the warehouse '
     'for a different reason. Subjective instruments, the sleepiness and perceived-exertion scales and '
     'the vigilance test, are the accepted references and they interrupt the work they measure, which '
     'makes them unusable as a continuous signal. Wearable physiological monitoring solves the continuity '
     'problem and creates an adoption one. And contactless sensing, taken modality by modality, has '
     'reached real technical maturity without anyone having pointed it at industrial fatigue.'),
    ('R', 90),
    ('R', 91),
    ('Rs', 92, [('Lidar gives three-dimensional gait measurement robust to illumination',
                 'Lidar gives three-dimensional gait measurement that is unaffected by illumination')]),
    ('R', 93),
    ('p',
     'The gap is therefore not a shortage of capable sensors. It is that nobody has fused them for this '
     'purpose. Existing multi-modal fatigue work is overwhelmingly contact-based or aimed at seated '
     'drivers, and the contactless studies are single-modality and laboratory-bound. The second gap is '
     'regulatory rather than technical: India’s data protection legislation of 2023 has created real '
     'uncertainty about workplace monitoring, and an architecture that extracts a derived score on the '
     'device and never transmits raw video is a different legal object from one that streams a camera '
     'feed to a server. That distinction is designed in here rather than argued for afterwards.'),

    ('h2', '3.3 The framework proposed'),
    ('p',
     'Figure 20 gives the proposed arrangement in one view. Four contactless modalities feed a single '
     'edge computing platform, a fused model produces one score per crossing, and that score drives a '
     'rest or rotation decision rather than a record. Each modality is there for a specific reason. A '
     'camera with on-device pose estimation recovers two-dimensional gait: stride, sway and cadence. A '
     'solid-state lidar recovers the same geometry in three dimensions and does not care about the '
     'lighting. A millimetre-wave radar at 60 GHz reaches heart and respiration rate through clothing, '
     'which neither of the other two can see. And a long-wave infrared camera reads facial skin '
     'temperature, which in the ambient conditions described above is likely to carry more information '
     'than it would in a temperate facility.'),
    ('F', 'fatga'),
    ('p',
     'Two design decisions are worth drawing out. The capture is fixed and single-subject: rather than '
     'tracking several people continuously across a floor, the node sits at one point everybody passes, '
     'an aisle end or a doorway, mounted two and a half to three and a half metres up and angled down, '
     'working at one to five metres. Each crossing then yields one clean measurement of one person. That '
     'trades coverage for tractability, and it is the trade the strand makes deliberately, because '
     'continuous multi-person tracking is a harder problem than the one being asked about and solving it '
     'is not a prerequisite for answering whether fatigue is legible at all.'),
    ('p',
     'The second is that every feature is referred to the worker’s own baseline, recorded at the '
     'start of their shift, before it reaches the model. That converts an absolute measurement, which '
     'varies enormously between people, into a within-subject change, which is the quantity the question '
     'is actually about. The fusion itself is a convolutional branch per stream followed by a recurrent '
     'stage over the sequence, with attention across the modalities so that the model can lean on '
     'whichever streams are usable when one of them is occluded. It produces a single number per '
     'crossing, computed on the node, and no raw video leaves it.'),
    ('p',
     'There is one constraint the design has to respect rather than exploit. Gait carries enough '
     'information to identify a person, and the point-cloud benchmark cited in Section 3.2 exists to '
     'demonstrate exactly that. A system installed to estimate fatigue must not become a system that '
     'recognises individuals, so the pipeline has to discard identity by construction rather than by '
     'policy. That is easier to design for at the start than to retrofit, and it constrains which '
     'features may be retained and what may be stored.'),

    ('h2', '3.4 How the framework would be validated'),
    ('p',
     'Figure 21 sets out the three objectives and, more usefully, what each one would be measured '
     'against. The right-hand column is the part that makes the strand falsifiable. Gait from the camera '
     'and the lidar is checked against marker-based motion capture, which is an external physical '
     'reference rather than another estimate. A subset of volunteers wears surface electromyography on '
     'the calf muscles and inertial bands at the same time as the contactless capture, so the proposed '
     'method is compared directly against the established contact method it proposes to replace, on the '
     'same subjects during the same task. Field deployment then runs in an operational, '
     'non-air-conditioned warehouse across thirty to fifty workers and several shifts, scored against '
     'the vigilance and sleepiness instruments.'),
    ('F', 'fatdes'),
    ('p',
     'The comparison that decides the thing is the last row. The fused score is required to beat four '
     'single-modality baselines, camera alone, lidar alone, radar alone and thermal alone, together with '
     'an ablation over the four. Setting that bar before any data is collected is deliberate, because it '
     'is exactly the comparison that becomes easy to avoid once a pipeline exists and produces '
     'plausible-looking numbers. A fused score that cannot beat the best single modality has bought '
     'nothing for four sensors and an edge processor.'),
    ('p',
     'One practical constraint sits across all of it. Simultaneously processing four high-bandwidth '
     'streams on a single edge platform generates heat, and a non-air-conditioned Indian warehouse above '
     '40 °C is precisely where that platform will throttle. That is a design constraint on the node '
     'rather than a footnote, and it is one of the reasons the hardware objective has to be completed and '
     'tested in situ before the algorithmic one means anything.'),

    ('h2', '3.5 Work done, and what comes next'),
    ('p',
     'What exists at the end of the year is the survey, the hypothesis it produced, and a full research '
     'proposal built on both. The survey covered sensor modality performance, multi-modal fusion '
     'architectures, occupational fatigue physiology, Indian industrial environmental conditions and '
     'the data protection position, searched between June and September 2026 across the Crossref and '
     'scite indexes on combinations of fatigue, gait, thermal imaging, millimetre-wave radar and lidar '
     'with industrial, occupational and warehouse qualifiers, admitting peer-reviewed work only. It is a '
     'bounded search rather than an exhaustive one and the gap it identifies should be read as such.'),
    ('p',
     'The technical feasibility argument rests entirely on other people’s results, and that is '
     'stated rather than blurred. Each of the four modalities has been demonstrated to high accuracy '
     'individually by established groups, and fusion using this class of architecture has been shown to '
     'outperform single-modality baselines in related fatigue tasks. None of that is evidence that the '
     'combination works here. It is evidence that the combination is worth attempting.'),
    ('R', 268),
    ('p',
     'The sequence matters more than the schedule. The capture node comes first, because until one '
     'exists there is no data of any kind. Per-modality laboratory validation comes second and is the '
     'step most likely to end the strand, which is a reason to reach it early rather than late: if two '
     'of the four modalities carry no usable fatigue signal on walking subjects, the design changes '
     'before anything is built around them. Fusion, the field deployment and the baseline comparison '
     'come last, because they are the only steps that need every preceding one to have worked.'),
]

BODY += [
    # ═════════════════════════════════════════════════════ CHAPTER 4 ══
    ('h1', 'Chapter 4  Conclusions and Objectives for the Years Ahead'),
    ('h2', '4.1 What the first year established'),
    ('R', 270),
    ('R', 271),
    ('p',
     'The monitoring strand adds a fifth, of a different kind. A complete system was taken from nothing '
     'to a deployment running unattended across four zones in two radio-isolated installations sharing '
     'one database, with three concurrent communication channels, two control paths and automatic '
     'recovery from a power interruption. That is an engineering result rather than a measured one, and '
     'the report is careful in Section 2.6 about the difference: the deployed logic has been shown to '
     'produce the configured states for the inputs present at an instant, and has not been shown '
     'responding to a change on a single time axis.'),

    ('h2', '4.2 What remains open, and why'),
    ('R', 272),
    ('R', 273),
    ('p',
     'Open items on the other two strands are smaller in scope but not in importance. The monitoring '
     'system reports a gas index that is a rescaled analogue count rather than a calibrated '
     'concentration; reports an ultraviolet irradiance whose responsivity coefficient is still set to '
     'one, so the figure is a voltage relabelled; has an operator off-command that the automatic law '
     'reverts on its next pass; and does not implement the lamp-failure detection that its irradiance '
     'measurement exists to support. All four are documented against the specific code paths involved, '
     'all four are fixable, and none should be carried into a second year. The fatigue strand has '
     'nothing to correct because it has nothing built, which is itself the thing to change.'),

    ('h2', '4.3 Objectives for the years ahead'),
    ('p',
     'The plan runs one strand at a time rather than all three at once, and Figure 22 lays it out. Each '
     'strand is carried on its own until it stands up by itself, and only then do they meet. That '
     'ordering is a judgement rather than a convention: a strand whose behaviour has not been '
     'characterised alone contributes nothing measurable to a combined system, and combining early would '
     'mean three partly-understood components whose failures could not be told apart.'),
    ('F', 'road'),
    ('lead', 'The robot.', 'Five things follow directly from Chapter 1, and they are given here in the '
             'order in which they unblock each other.'),
    ('R', 262),
    ('R', 263),
    ('R', 264),
    ('R', 265),
    ('R', 266),
    ('lead', 'The monitoring system.', 'Four items, in order of how much each one changes what the '
             'system can honestly claim. The gas channel has to be driven from the calibration that is '
             'already computed and stored rather than from a rescaled count, and the ultraviolet channel '
             'has to be calibrated against a reference radiometer at a fixed geometry, because until '
             'both are done no measurement from the unit can be quoted as a quantity. Lamp-failure '
             'detection comes next and is the capability that distinguishes the unit from a timer: once '
             'the relay has been closed longer than the lamp strike time, irradiance above a threshold '
             'should be required, and its absence should raise an alert. Third, the cellular inbox poll '
             'has to stop blocking the main loop, which is roughly six lines and fixes the command '
             'latency and the publish jitter at the same time. Transfer to cold-chain and '
             'controlled-atmosphere rooms comes fourth, and is the point at which the architecture is '
             'tested against an application it was not built for.'),
    ('lead', 'The fatigue strand.', 'The sequence is set out in Section 3.5 and is not repeated here, '
             'except for the one decision that belongs in a plan rather than in a chapter. The '
             'per-modality laboratory validation, and in particular the comparison against surface '
             'electromyography on the same subjects during the same task, is scheduled early, in the '
             'second year, specifically because it is the step most likely to show that the approach '
             'does not work. A negative result reached in year two is a useful contribution and leaves '
             'time to act on it. The same result reached in year four is not.'),

    ('h2', '4.4 Where the three converge'),
    ('p',
     'The end state this project is aimed at is one facility that knows three things about itself at the '
     'same time: where its autonomous machines are and what they are carrying, what the air is doing in '
     'every storage area rather than at a handful of instrumented points, and how hard the people '
     'sharing those aisles are working. Each of the three chapters above is one of those, taken far '
     'enough that it can be measured on its own terms.'),
    ('p',
     'The mechanism by which they join is not a piece of integration software. It is that the robot '
     'becomes the mobile element of the monitoring system, carrying the same sensor complement through '
     'the spaces no fixed node will ever be bolted to and reporting into the same database on the same '
     'schema, while the fatigue sensing sits at the aisle ends the robot is already navigating between. '
     'None of that requires anything to be invented. It requires the navigation layer to be finished, '
     'the monitoring channels to be calibrated, and the fatigue pipeline to have been shown to work, '
     'which is the content of the three plans above.'),
    ('p',
     'The honest summary of the position at the end of year one is that the first strand has a built '
     'machine and a set of measured limits, the second has a running system and a list of defects it '
     'should not carry forward, and the third has an argument. Year two turns the first into a robot '
     'that navigates a saved map, the second into a system whose numbers can be quoted, and the third '
     'into data. Only then is there anything to converge.'),

    ('h1', 'Bibliography'),
] + [('ref', n) for n in range(276, 313)]
