# Figure 2 is the real deployed-electronics circuit diagram, not the
# matplotlib software-architecture reconstruction this file used to draw —
# docs/hardware/nab_circuit_diagram.png, generated by
# docs/hardware/circuit_diagram.py directly from the repo's own hardware docs
# (Master_Reference.md, Bench_Test_Map.md, RMCS-2086_Encoder_Replacement.md),
# with real pin numbers, wire colours and rail voltages rather than a
# schematic approximation. Kept as a no-op so a full regeneration run does not
# overwrite the real diagram; edit docs/hardware/circuit_diagram.py instead if
# the wiring changes.
print('fig02: real circuit diagram, not generated here — see docs/hardware/nab_circuit_diagram.png')
